package findBlood;

//package com.sendSms.jsp;
import no.vianett.sms.SmsEventListener;
import no.vianett.sms.Sms;
import no.vianett.sms.SmsEvent;
import no.vianett.sms.component.SmsTransceiver;
import no.vianett.sms.log.SmsScreenLogger;
import no.vianett.sms.event.SmsDeliveredEvent;
import no.vianett.sms.event.SmsSendingFailedEvent;
import no.vianett.sms.event.SmsDeliveryFailedEvent;
 
public class SmsSender implements SmsEventListener
{
    private SmsTransceiver transceiver = null;
    private Object link = null; // Just to keep this object alive.
    private int counter = 0;
    private static String mobileNo;
    private static String hospitalName;
    private String message; 
    public SmsSender()
    {
        this.link = this; // Keeps this object alive.
        this.transceiver = SmsTransceiver.getInstance(); // Get the transceiver object.
 
        // Initialize transceiver.
        String smsHost = "cpa.vianett.no";
        String smsPort = "31337";
        String smsUsername = "sahuprashant03@gmail.com";
        String smsPassword = "z0zdn";
        this.transceiver.initialize( smsHost, Integer.parseInt( smsPort ), smsUsername, smsPassword, new SmsScreenLogger() );
 
        this.transceiver.addSmsEventListener( this ); // Registrer this class as listener for SMS events.
 
        // Send message
        message="FIND YOUR BLOOD \n Hey Donor! There is an urgent need of  blood in "+hospitalName+".\nPlease donate blood asap.";
        System.out.println("From SMSsender"+message+" "+mobileNo);
        Sms sms = new Sms();
        sms.setId( ++this.counter );
        sms.setReplyPath( 100 );
        sms.setSender( "1963" ); // Set the sender number.
        sms.setMessage(message);
        //String mess="Hello ";
        sms.setRecipient(mobileNo); // The recipients phone number.
 
        this.transceiver.send( sms );
    }
     public  static void generateMessage(String mobile,String hospitalNm)
    {
        mobileNo=mobile;
        hospitalName=hospitalNm;
    }
 
 
    // Just make new instance of this class.
    public static void main( String[] args ){ new SmsSender(); }
 
    /**
    * Listener.
    *
    * @param event a <code>no.vianett.sms.SmsEvent</code>
    */
    public void eventHappened( SmsEvent event )
    {
        if( event instanceof SmsDeliveredEvent )
        {
            System.out.println( "Sms delivered." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsSendingFailedEvent )
        {
            System.out.println( "Sms sending failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Return code : " + ( ( SmsSendingFailedEvent ) event ).getReturnCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
        else if( event instanceof SmsDeliveryFailedEvent )
        {
            System.out.println( "Sms delivery failed." );
            System.out.println( "Refno : " + event.getReferenceId() );
            System.out.println( "Error code : " + ( ( SmsDeliveryFailedEvent ) event ).getErrorCode() );
            System.out.println( "Sms generated by : " + event.getSource().getClass() );
        }
    }
 
}